name: Security

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  schedule:
    - cron: '0 2 * * 1'

jobs:
  security:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'
        cache: true
    
    - name: Download dependencies
      run: go mod download

    - name: Install govulncheck
      run: go install golang.org/x/vuln/cmd/govulncheck@latest
    
    - name: Run govulncheck
      run: govulncheck ./...
    
    - name: Check for known vulnerabilities in dependencies
      run: |
        go list -json -m all > go-modules.json
        
    - name: Upload dependency list
      uses: actions/upload-artifact@v4
      with:
        name: go-modules
        path: go-modules.json
        retention-days: 7
